#consultas sql jugador
sql.select.requestAllUsers= SELECT * FROM Jugadores
sql.insert.createNewUser= INSERT INTO Jugadores (Correo, Nombre_y_apellidos, Fecha_de_nacimiento, Fecha_de_inscripcion) VALUES (?,?,?,NULL)
sql.update.modifyUser= UPDATE Jugadores SET Nombre_y_apellidos=?, Fecha_de_nacimiento=? WHERE Correo=?
sql.select.requestUser= SELECT * FROM Jugadores WHERE Correo = ?
sql.update.updateFechaInscripcion= UPDATE Jugadores SET Fecha_de_inscripcion=? WHERE Correo=?

#consultas sql pista
sql.insert.createPista= INSERT INTO Pistas (Nombre, Estado, Tipo, Tamaño, Jugadores_maximos) VALUES (?,?,?,?,?)
sql.insert.createNewMaterial= INSERT INTO Materiales (Uso, Tipo, Estado) VALUES (?,?,?)
sql.select.requestPistasNoDisponibles= SELECT * FROM Pistas WHERE Estado = false
sql.select.requestPistasNoDisponiblesMateriales= SELECT * FROM Materiales, Materiales_Pistas WHERE Nombre_pista= ? AND Id=Id_material
sql.select.requestMaterialesDisponibles= SELECT * FROM Materiales WHERE Estado = "DISPONIBLE"
sql.select.requestPistasJugadoresTamaño= SELECT * FROM Pistas WHERE Jugadores_maximos>= ? AND Tamaño= ?
sql.select.requestPistasJugadoresTamañoMateriales= SELECT * FROM Materiales, Materiales_Pistas WHERE Nombre_pista= ? AND Id=Id_material
sql.insert.assignNewMaterialToPista= INSERT INTO Materiales_Pistas (Id_material, Nombre_pista) VALUES (?,?)
sql.update.assignNewMaterialToPista= UPDATE Materiales SET Estado=? WHERE Id=?
sql.updateEstadoMaterial= UPDATE Materiales SET Estado=? WHERE Id=?
sql.select.requestPista= SELECT * FROM Pistas WHERE Nombre= ?
sql.select.requestMaterial= SELECT * FROM Materiales WHERE Id= ?
sql.select.requestContTipoMaterial= SELECT * FROM Materiales, Materiales_Pistas WHERE Tipo=? AND Id=Id_material AND Nombre_pista=?

#consultas sql reservas 
sql.select.requestContReservasFuturas= SELECT * FROM Reservas WHERE Fecha > ?
sql.select.requestContReservasFechaNombre= SELECT * FROM Reservas WHERE Fecha = ? AND Nombre_pista = ?
sql.update.modificarReserva1= UPDATE Reservas SET Fecha = ?, Hora = ?, Duracion = ?, Precio = ? WHERE Nombre_pista = ? AND Fecha = ? AND Hora = ?
sql.update.modificarReserva2= UPDATE Reserva_Bonos SET Fecha = ?, Hora = ? WHERE Nombre_pista = ? AND Fecha = ? AND Hora = ?
sql.delete.cancelarReserva1= DELETE FROM Reservas WHERE Nombre_pista = ? AND Fecha = ? AND Hora = ?
sql.select.cancelarReserva= SELECT * FROM Reserva_Bonos WHERE Nombre_pista = ? AND Fecha = ? AND Hora = ?
sql.delete.cancelarReserva2= DELETE FROM Reserva_Bonos WHERE Nombre_pista = ? AND Fecha = ? AND Hora = ?
sql.update.cancelarReserva= UPDATE Bonos SET Sesiones_disponibles = Sesiones_disponibles + 1 WHERE Id = ?
sql.insert.createNewBono= INSERT INTO Bonos (Correo_usuario, Tipo, Sesiones_disponibles) VALUES (?,?,5)
sql.insert.createReservaIndividual= INSERT INTO Reservas (Correo_usuario, Nombre_pista, Fecha, Hora, Duracion, Numero_de_adultos, Numero_de_niños, Descuento, Precio ) VALUES (?,?,?,?,?,?,?,?,?)
sql.insert.createAñadirReservaABono1= INSERT INTO Reserva_Bonos (Id_bono, Nombre_pista, Fecha, Hora) VALUES (?,?,?,?)
sql.insert.createAñadirReservaABono2= INSERT INTO Reservas (Correo_usuario, Nombre_pista, Fecha, Hora, Duracion, Numero_de_adultos, Numero_de_niños, Descuento, Precio ) VALUES (?,?,?,?,?,?,?,?,?)
sql.update.createAñadirReservaABono= UPDATE Bonos SET Sesiones_disponibles = Sesiones_disponibles-1 WHERE Id=?
sql.select.requestReservasByFechaPista= SELECT * FROM Reservas WHERE Fecha = ? AND Nombre_pista = ?
sql.select.requestBonoCorreoPista= SELECT * FROM Pistas, Bonos WHERE Bonos.Tipo=Pistas.Tamaño and Correo_usuario= ? AND Nombre= ? AND Sesiones_disponibles>0 and (Fecha_caducidad > ? or Fecha_caducidad is null)
sql.update.updateFechaCaducidad= UPDATE Bonos SET Fecha_caducidad = ? WHERE Id = ? and Fecha_caducidad is null
sql.select.requestBonos= SELECT * FROM Bonos Where Correo_usuario = ?